# Generated by Django 4.2.4 on 2023-08-08 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
    ]
