# Generated by Django 4.2.3 on 2023-08-09 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_remove_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
    ]
